### ISSUE TITLE
linux系统浏览器的UA无法识别

### ISSUE THREAD

**Issue by zhuyingda** [hotoo/detector#100]
例如：
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by allenfantasy** [comment]
我把这两个 userAgent 字符串放到了测试用例里面跑了一下：

`device` 的值为 `na/-1`（如果是 linux 的话应该返回 `pc/-1`）

检查了一下代码实现，判断 device 的值为 pc 的 [规则](https://github.com/hotoo/detector/blob/master/lib/web-rules.js#L38) 为：

```
["pc", "windows"],
```

其他字段个人认为都是合理的。

附上测试得到的返回值：

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

```
{
    device: "na/-1",
    os: "linux/-1",
    browser: "chrome/47.0.2526.106;47.0.2526.106;o",.
    engine: "webkit/537.36;537.36;o",
}
```

> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

```
{
    device: "na/-1",
    os: "linux/-1",
    browser: "firefox/45.0;45.0;o",.
    engine: "gecko/45.0.20100101;45.0.20100101;o",
}
```

>

**Comment by zhuyingda** [comment]
我的网站使用detector过滤ua，防御一些低端的curl野爬。目前已经有很多人反应网站打不开，全都是linux系统的用户。
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
这个ua的用户的具体设备信息是：
OS: Ubuntu Desktop 15.10 x86_64     kernal: 4.2.0-27-generic
浏览器:  Google Chrome	47.0.2526.106 (Official Build) (64-bit)

但是device返回na 这个应该是有些问题的吧？

**Comment by zhuyingda** [comment]
是否应该在device中加入 ["linux","linux"]类似这样的？

**Comment by allenfantasy** [comment]
我觉得你暂时可以先通过 os 来判断. 在 device 的值为 na 时，检查 os 是否等于 linux，来防止误杀用户。

至于这个 device 字段的问题，我看看有没有时间提一个 PR.

**Comment by hotoo** [comment]
包括 Linux 桌面系统和很多移动操作系统（包括 Android）都有 `linux` 特征，如果不能区分这两者的话，增加一个 `linux` device 似乎没意义。

**Comment by hotoo** [comment]
可以考虑使用其他信息来判断机器人爬虫。
