### ISSUE TITLE
windows下怎么 make啊？

### ISSUE THREAD

**Issue by heheguai** [hotoo/detector#101]
有 编译好的版本吗？

**Comment by army8735** [comment]
https://github.com/bmatzelle/gow

**Comment by heheguai** [comment]
3Q

**Comment by heheguai** [comment]
detector@2.4.5 test E:\桌面\detector-master
> make test

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ npm ERR! Test failed.  See above for more details.

**Comment by hotoo** [comment]
安装好 npm 和 Cygwin 或 Gow，

```bash
$ npm install pinyin
```

**Comment by heheguai** [comment]
3Q  这个 完了 还要 python  之后还不知道要配什么 。。。  求好心人给个编译好的

**Comment by heheguai** [comment]
完了还是 
> detector@2.4.5 test E:\桌面\detector-master
> make test

make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x4227d3)
npm ERR! Test failed.  See above for more details.

**Comment by hotoo** [comment]
你为什么要 make test？安装好 node + npm ，然后 `npm i detector`, `require('detector')` 不就可以了么？

**Comment by heheguai** [comment]
@hotoo 我想在浏览器中直接使用

**Comment by allenfantasy** [comment]
@heheguai 可以考虑使用 [Browserify](http://browserify.org/) 或者 [Webpack](https://webpack.github.io/) 来引入 detector 的包，编译出的 js 脚本就可以在浏览器中运行。

另外，由于 detector 是用 ES6 编写的，所以你还需要 ES6 的支持（Babel），可以查阅两种工具结合 Babel 的使用。

**Comment by hotoo** [comment]
@allenfantasy +1
