### ISSUE TITLE
[Bug] Detected data wrong

### ISSUE THREAD

**Issue by Luchillo** [hotoo/detector#106]
**Environment data:**
OS: Mac OS X El Capitan
Browser: Chrome  52.0.2743.116

**Issue:**
Data detected is wrong, putting aside the engine and device properties, the output expected is OS with Mac at least, and browser the version above, however output states ios 9.1 and safari 9:

```json
{
	"device": {
		"name": "iphone",
		"version": -1,
		"fullVersion": "-1",
		"iphone": -1
	},
	"os": {
		"name": "ios",
		"version": 9.1,
		"fullVersion": "9.1",
		"ios": 9.1
	},
	"engine": {
		"name": "blink",
		"version": 601.1,
		"fullVersion": "601.1.46",
		"mode": 601.1,
		"fullMode": "601.1.46",
		"compatible": false,
		"blink": 601.1
	},
	"browser": {
		"name": "safari",
		"version": 9,
		"fullVersion": "9.0",
		"mode": 9,
		"fullMode": "9.0",
		"compatible": false,
		"safari": 9
	}
}
```

**Comment by hotoo** [comment]
1. What detector version is?
2. Please vist http://hotoo.me/detector/examples/ and feedback output information here.

Thank you very much :)

**Comment by Luchillo** [comment]
1. Acording to the package.json is 2.5.0 which is the latest release to date.
2. The example gives accurate data, tomorrow i'll test in the pc that showed the error, currently i'm in windows and the wrong data happened in Mac.

**Comment by hotoo** [comment]
Anything updates?

**Comment by hotoo** [comment]
@Luchillo Anything updates?

**Comment by Luchillo** [comment]
@hotoo Man idk why i had those results but after testing both in web and in an Ionic 2 app (which is a hybrid app that works like a small browser serving up the web app like if it were a native app) it works good.

Maybe i had an older version and i did npm update after getting those tests, anyway it's working as expected, thanks.
