### ISSUE TITLE
不能识别2345浏览器

### ISSUE THREAD

**Issue by iloveyo123u1** [hotoo/detector#110]
建议参考

http://blog.csdn.net/huangxiongbiao/article/details/41478235
https://github.com/zsxsoft/useragent.js

**Comment by hotoo** [comment]
#39

**Comment by hotoo** [comment]
你是什么样的需要要识别这个浏览器？

**Comment by iloveyo123u1** [comment]
因为这个浏览器市场份额不小， 有个服务，要针对他们，显示不同的信息
