### ISSUE TITLE
希望增加手机百度识别

### ISSUE THREAD

**Issue by 599316527** [hotoo/detector#111]
UA 中的特征是 `baiduboxapp/8.4`

**Comment by hotoo** [comment]
请提供完整的 ua 字符串

**Comment by 599316527** [comment]
* iOS: `Mozilla/5.0 (Linux; Android 7.0; E6683 Build/32.3.A.0.376) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/35.0.1916.138 Mobile Safari/537.36 T7/7.4 baiduboxapp/8.4 (Baidu; P1 7.0)`
* Android: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304 baiduboxapp/0_01.0.4.8_enohpi_4331_057/1.3.01_1C2%259enohPi/1099a/5H651T3G1F97R4K26P7L7NDG6035130273SB73A96IJVT01J9UY/1`
