### ISSUE TITLE
增加对 360 手机的识别

### ISSUE THREAD

**Issue by welefen** [hotoo/detector#116]
`User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; 1509-A00 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.95 Mobile Safari/537.36 PICASSO@360 mso_app (4.3.2)`

关键字符串为 `1509-A00`，正则可以为 `/\d{4}\-[A-Z]\d{2} Build/`

**Comment by hotoo** [comment]
这个 `1509-A00` 是什么东西？我看 360 的 UA 里并没有这个

https://github.com/hotoo/detector/wiki/360

**Comment by welefen** [comment]
@hotoo 这个是 360 手机（奇酷手机）的各个型号的标识

**Comment by welefen** [comment]
@hotoo 我看 commit 里有 oppo 检测的提交，能发个新版本么?
