### ISSUE TITLE
360浏览器的识别

### ISSUE THREAD

**Issue by hotoo** [hotoo/detector#6]
360浏览器会针对不同域名修改 UA，在部分网站可以检查到 360se, 360ee 等信息，而且有特定的 `windows.external` 可用，但是大部分网站没有提供这些特性。

包括百度统计等在内，都不能正常识别 360.

但是 cnzz 对外显示的数据却一直比较正常（最早 3Q 大战时 cnzz 统计的 360 同样出现大幅度下降并有新闻报道 360 份额急剧下降至 5% 左右，使用的就是 cnzz 的数据。但是现在看 cnzz 的报表却没有什么异常波动。

不知道是 cnzz 有什么特殊检测手段（看了 js 源码没看到什么特别的），还是商业上有合作（360浏览器访问 cnzz 同样没有声明 UA 和 `window.external`）？
### 参考链接
- [360 浏览器占有率从 2012 年 7 月的 22.53% 骤降到 9 月的 2.44%，原因是什么？](http://www.zhihu.com/question/20556578/answer/15472681)
- [偏门方法解决无法判断360浏览器的问题](http://www.36ria.com/5661) - `res://360se.exe/2/2025`
- [JavaScript 判断 Chrome 内核的 360 浏览器](http://loo2k.com/blog/detect-chrome-core-360-browser/) - `navigator.mimeTypes['application/x-shockwave-flash']`

**Comment by zhishaofei3** [comment]
@hotoo 有点意思

**Comment by mumuy** [comment]
var is360 = window.showModalDialog && window.chrome;
这个可以的！

**Comment by jjj201200** [comment]
来自360的商城
https://ext.chrome.360.cn/webstore/category/%E5%B0%8F%E5%B7%A5%E5%85%B7/%E7%BC%96%E8%BE%91%E6%8E%A8%E8%8D%90

(function(){
    var _is360chrome=false;
    try{
      if(typeof( chrome )!= "undefined" && typeof( chrome.webstorePrivate)!='undefined' && typeof (chrome.webstorePrivate.beginInstallWithManifest3)!='undefined'){
        _is360chrome=true;
      }else {
        _is360chrome=navigator.userAgent.toLowerCase().indexOf('360ee')!=-1;
      }
    }catch(e){}
    return !_is360chrome;
  })()

**Comment by chanjsq** [comment]
@jjj201200 机智！优秀

**Comment by crcong** [comment]
2021-01-20，此方法有用，来自 https://juejin.cn/post/6844903504968957965
/**
 * 判断是否为360极速浏览器，民间方法
 * @returns { Boolean } - 判断结果
 */
const is360Chrome = () => {
    const uas = navigator.userAgent.split(' ');
    let result = false;
    // 排除ua自带标志的双核浏览器, 余下chrome, chromium及360浏览器
    if (uas[uas.length - 1].indexOf('Safari') == -1) {
        return result;
    }
    for (const key in navigator.plugins) {
        if (!Object.prototype.hasOwnProperty.call(navigator.plugins, key)) {
            continue;
        }
        // np-mswmp.dll文件在chromium及chrome未查询到
        if (navigator.plugins[key].filename === 'np-mswmp.dll') {
            return true;
        }
    }
    return result;
};
