### ISSUE TITLE
NODE ONLY 指得什么意思？

### ISSUE THREAD

**Issue by luciy** [hotoo/detector#74]
如题！

**Comment by Minwe** [comment]
Node.js only

**Comment by hotoo** [comment]
detector 这个模块适用于 Web 和 Node 端，但是考虑到规则数量对网络和计算性能的影响，Web 端只使用了部分常用规则，能够识别大多数客户端。

而 Node 端是安装到本地，没有 Web 端的这些顾虑，可以增加更多的规则。

`NODE ONLY` 就是这些 Web 端没有，而 Node 端拥有的规则。
换句话说，就是这些客户端不能被 Web 版的 detector 识别，但是能被 Node 版的 detector 识别。

**Comment by luciy** [comment]
感谢大大得回答，micromessenger 判断微信中打开，通过navigator.userAgent也是从Web 端判断的啊。但是被分到了 NODE ONLY中。

**Comment by hotoo** [comment]
你可以根据自己的业务场景， fork 一份并把需要的规则调整到 Web/Node 版中。

**Comment by luciy** [comment]
thank you 谢谢大大！
