### ISSUE TITLE
魅族手机检测没有覆盖所有机型，甚至没有覆盖大部分新机型。

### ISSUE THREAD

**Issue by bammoo** [hotoo/detector#75]
RT。

**Comment by hotoo** [comment]
请使用魅族手机访问 http://spmjs.io/docs/detector/examples/ 
并反馈检测到的相关信息，谢谢你的贡献 ：）

**Comment by bammoo** [comment]
@hotoo 好的，不过，我手上只有 mx3 mx4 魅蓝 ，更多的看这里： http://www.zhihu.com/question/23265851/answer/24081540

**Comment by hotoo** [comment]
http://bbs.meizu.cn/viewthread.php?tid=3965020&highlight=useragent

魅族官方论坛都没人回，真是绝了。

**Comment by hotoo** [comment]
http://bbs.meizu.cn/thread-3342317-1-1.html

**Comment by hotoo** [comment]
我测试了上面提供的 UA，都能准确识别魅族设备及其版本。

不知道你说的新机型是什么样的，请提供你觉得没识别正确的检测信息，谢谢。

**Comment by hotoo** [comment]
测试地址 http://spmjs.io/docs/detector/examples/tests.html

**Comment by bammoo** [comment]
根据你最新修改的，mx3 和 m1 note 都可以了，但 mx4 还不行：

Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; MX4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36


我看了一下：这一段好像没多少用处：/\bmeizu[\/ ]([a-z0-9]+)\b/。
我现在的匹配规则是：

/(m1\snote|MEIZU|MX4|M040|M045|M351|M353|M355|M356)(\s)/

^_^ 我忽视了 M9 之类的老机型。

**Comment by hotoo** [comment]
你这样罗列也不是办法，出了新版机型又要改。

话说魅族的 UA 真是够贱的。
