### ISSUE TITLE
package.json增加broswer字段，支持npm源

### ISSUE THREAD

**Issue by shepherdwind** [hotoo/detector#78]
现在依赖了commander和color，这样无法通过npm 的方式require了、webpack打包。

修改方式：

```
  "browser": {
    "commander": false,
    "color": false
  }
```

**Comment by hotoo** [comment]
https://github.com/hotoo/detector/commit/59298d8ab1b1b75b725326cfe4de8e0e4d26d8f7

**Comment by hotoo** [comment]
detector@2.2.3

应该是 colors，下回之间提交 PR 吧。
