### ISSUE TITLE
新版本的代码在浏览器中的使用

### ISSUE THREAD

**Issue by linrubo** [hotoo/detector#89]
公司的sdk中一直在用这个库，最近决定升级下，发现变化好大，新增很多新语法特性。
问下现在的版本有没有可以在浏览器（低版本）中直接可用的，或者如何转换成在浏览器中直接可用的版本。

**Comment by hotoo** [comment]
#88 

好吧，看来有必要提供一个打包好的版本。

**Comment by hotoo** [comment]
https://github.com/hotoo/detector/tree/gh-pages
