### ISSUE TITLE
使用 web-detector.js 时，当 userAgent 被判定为 IE 内核时代码报错

### ISSUE THREAD

**Issue by allenfantasy** [hotoo/detector#92]
### 具体信息

* 报错位置：`web-detector.js` 的 [第72行](https://github.com/hotoo/detector/blob/master/lib/web-detector.js#L72)
* 错误信息：`ReferenceError: name is not defined`

在代码中检查了，确实没有 name 的定义，好像是一个 bug?

**Comment by hotoo** [comment]
2.4.3

**Comment by allenfantasy** [comment]
@hotoo :+1: 效率好高 :)
