### ISSUE TITLE
检测摩托罗拉（motorola）时有无法识别的 userAgent

### ISSUE THREAD

**Issue by allenfantasy** [hotoo/detector#95]
RT >3<

在开发检测脚本，进行 userAgent 调研时，发现有关于摩托罗拉的 userAgent 如下（出处在 [这里](http://www.webapps-online.com/online-tools/user-agent-strings/dv/brand294288/motorola-moto-g)）

> Mozilla/5.0 (Linux; Android 4.4.2; XT1033 Build/KXB20.25-1.31) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.136 Mobile Safari/537.36

不是很确定这个 userAgent 的真实性。但我在查阅代码时，发现检测摩托罗拉的 [代码](https://github.com/hotoo/detector/blob/master/lib/rules.js#L141) 的表达式如下：

```js
if (/\bmot[\-]([a-z0-9]+)/.test(ua)) {
  return /\bmot[\-]([a-z0-9]+)/;
} else if (/ (xt\d{3}) build/.test(ua)) {
  return / (xt\d{3}) build/;
}
```

在判断 `xt` 时写死了是3个数字, 是否可以考虑改成 `/xt\d{3,4} build/`? 这样就可以兼容上面的 userAgent.

Thx!

**Comment by hotoo** [comment]
2.4.4 这种以后可以直接提交 MR

**Comment by allenfantasy** [comment]
@hotoo 好啊，谢谢 :)
