### ISSUE TITLE
ie 7,8有问题，Object.defineProperty无效

### ISSUE THREAD

**Issue by tokenian** [hotoo/detector#98]
如题，ie7/8是没有定义对象property属性的，所以直接运行报错。
能不能写下如何基于spm做的开发，我不知道是不是我安装的不对，我用spm build，没搞懂为什么？另外经过测试，iOS下chrome浏览器的userAgent带Ctriox(记不清了)，无法检测出来，结果是webview

**Comment by hotoo** [comment]
1. 用 es5 / es6 shim
2. 请提供有效信息，否则无法反馈。

**Comment by allenfantasy** [comment]
如果需要兼容 IE 8 或以下的浏览器，用 es5 / es6 shim 就可以了。

我这边使用时用了 Webpack + Babel 的方式进行开发，需要用到的是 Babel 的 loose mode. 详见 [这篇文章](http://www.2ality.com/2015/12/babel6-loose-mode.html)
