### ISSUE TITLE
如何判断手机QQ

### ISSUE THREAD

**Issue by beyondghx** [hotoo/detector#99]
在browser里面只看到了QQ浏览器，但是没有看到手Q的标识符。是否是没有自带判断手机QQ的rules?

**Comment by allenfantasy** [comment]
@beyondghx

browser 里面的检查方式包含了手机 QQ 的检查，但如果需要单独分开的话也可以直接用  `MQQBrowser` 这个关键字

**Comment by hotoo** [comment]
什么用途？如果你要的是『手机QQ』，可以判断『手机』 && 『QQ』

```js
detector.browser.qq && (
  detector.os.ios ||
  detector.os.android ||
  ...
)
```

**Comment by linrubo** [comment]
qq的webview不会屏蔽广告，但是qq浏览器会，还是有必要区分下吧

**Comment by hotoo** [comment]
@linrubo 你说的 QQ 的 WebView 跟手机 QQ 不是一回事吧？你后面说的 QQ 是手机版还是 PC 版的？

另外如果要区分这些的话，是否要分 Windows 版，Mac 版，Linux 版？这个信息通过 os 来判断是不是合适点？

**Comment by allenfantasy** [comment]
个人觉得需要先确定的一个问题是： `qq webview` 是否使用了和 qq 浏览器相同的内核（换句话说，是否套了一个 qq 浏览器在里面）。

区分 Windows / Mac / Linux 自然用 os 就可以了。

不过怎样能够识别 webview 倒是一个非常有趣的问题…… @hotoo 想问下你有没有这方面的实践经验？

**Comment by hotoo** [comment]
据我所知，iOS 的 WebView 是系统统一提供的，[这](https://github.com/hotoo/detector/issues/25#issuecomment-19673425) 是 3 年前的分析，最近没有关注，大家如果有兴趣可以再分析下，期待有相关分享到这里 ：）
